[default]

[default.extend-words]
# Thanks to base yamls.
idae = "idae"
# Some variables are called "matc" because "match" is reserved in Rust.
matc = "matc"
restat = "restat"

[files]
extend-exclude = [
    "serpent-style/**/*"
]