[workspace]
members = [
    "container",
    "boulder",
    "dag",
    "moss",
    "stone",
    "tui",
    "vfs",
]
default-members = [
    "moss"
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
bitflags = "2.4.1"
bytes = "1.5.0"
chrono = "0.4.30"
clap = { version = "4.4.8", features = ["derive"] }
crossterm = "0.27.0"
indicatif = "0.17.7"
itertools = "0.11.0"
futures = "0.3.28"
hex = "0.4.3"
log = "0.4"
nix = { version = "0.27.1", features = ["user", "fs", "sched", "process", "mount", "hostname"] }
once_cell = "1.18.0"
petgraph = "0.6.4"
rayon = "1.8"
reqwest = { version = "0.11.22", default-features = false, features = ["rustls-tls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
sha2 = "0.10.8"
sqlx = { version = "0.7.3", features = ["sqlite", "chrono", "runtime-tokio"] }
thiserror = "1"
tokio = { version = "1.34", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["time"] }
tokio-util = { version = "0.7.9", features = ["io"] }
url = { version = "2.4.1", features = ["serde"] }
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
zstd = "0.12.4"

[profile.release]
lto = 'thin'

[profile.packaging]
inherits = "release"
lto = true
codegen-units = 1
opt-level = 3
# allow packaging system to do it
strip = "none"
debug = true

