[package]
name = "triggers"
version = "0.1.0"
edition.workspace = true

[dependencies]
fnmatch = { version = "0.1.0", path = "../fnmatch" }
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true