[package]
name = "boulder"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
container = { path = "../container" }
moss = { path = "../moss" }

clap.workspace = true
tokio.workspace = true
