name: Nightly Build

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Project

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      run: cargo +nightly -Z build-std=std build --target=x86_64-unknown-linux-musl --profile packaging; ls -la; strip moss-rs; ls -la
