name: Nightly Build

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Project

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install musl
      run: sudo apt-get install musl-tools

    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-linux-musl
        components: rust-src

    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      run: |
        cargo +nightly -Z build-std=std build --target=x86_64-unknown-linux-musl --profile packaging
        mkdir release
        strip target/x86_64-unknown-linux-musl/packaging/moss -o release/moss
        sha256sum target/x86_64-unknown-linux-musl/packaging/moss > release/moss_sha256sum.txt
        ls -la release

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v6.1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: 'Clean up nightly releases'
    #   uses: dev-drprasad/delete-older-releases@v0.3.2
    #   with:
    #     keep_latest: 5
    #     delete_tags: true
    #     delete_tag_pattern: nightly
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Upload binaries to nightly release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: release/mos*
    #     file_glob: true
    #     tag: ${{ github.ref }}
    #     overwrite: true
