name: Release

on:
  push:
    tags:
      - v0.*
      - v1.*
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    runs-on: ubuntu-latest
    name: Build release binaries

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install musl
      run: sudo apt-get install musl-tools

    - name: Install Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-linux-musl
        components: rust-src

    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/

    - name: Build project
      run: |
        cargo +nightly -Z build-std=std build --target=x86_64-unknown-linux-musl --profile packaging
        strip target/x86_64-unknown-linux-musl/packaging/moss
        mkdir release && cd release
        tar czvf moss.tar.gz -C ../target/x86_64-unknown-linux-musl/packaging moss
        sha256sum moss.tar.gz > moss.tar.gz.sha256

    - name: Upload binaries to nightly release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/moss*
        file_glob: true
        tag: ${{ github.ref_name }}
        release_name: "${{ github.ref_name }}"
